[package]
name = "lz_interval_tree_clock"
version = "0.1.0"
authors = ["Luke Horsley <luke.horsley@alpha9software.com>"]

[dependencies]
failure = "0.1.3"
lazy_static = "1.2.0"
serde = { version = "1.0.80", features = ["rc"] }
serde_derive = "1.0.80"

[dev-dependencies]
matches = "0.1.8"